### ISSUE TITLE
Zooming causes timelines to overflow on the right side of the graph

### ISSUE THREAD

**Issue by otabekgb** [tanganellilore/visavail#2]

**Comment by tanganellilore** [comment]
Please provide me an image of this problem o jsfield or similar to reproduce the error.

Thanks

**Comment by tanganellilore** [comment]
Hi @otabekgb,

I'm not understand where is the problem.
But I reworked on blocks's drawing in the last two release.

In the last release the bug still present?
thanks

**Comment by otabekgb** [comment]
I think you can close this, at the moment I don't see this problem any more.
