### ISSUE TITLE
support 24 h format in x axes

### ISSUE THREAD

**Issue by otabekgb** [tanganellilore/visavail#3]

**Comment by tanganellilore** [comment]
Hi @otabekgb,

I know this "problem". In these days I restore the options for customize the ticks format date for hours, minutes, seconds.


For other parameter for example days, month, year actually I use moment for  internati al graph. 

In next update I also try to create a automatic parsing  for hours and minutes ticks with moment 18n file. 

Stay tuned
:-)

**Comment by tanganellilore** [comment]
hi @otabekgb .
Actually the format for x axes depend from moment library. I update the lib with support to moment locale . Default value is autodetect from browser language, you can change manually locale with the _"moment_locale"_ options.

If you need to customize also the format date/hour for x axes you can use the relative options implemented in the lib _"custom_time_format"_ . 

For the moment I close this issue

**Comment by otabekgb** [comment]
perfect, I cannot thank you enough. Please, keep on your wonderful work
