### ISSUE TITLE
On the left(start of chart) some time segments dropped

### ISSUE THREAD

**Issue by otabekgb** [tanganellilore/visavail#4]
If you see at the bottom there is drilldown of SIKO Position 1(SIKO client 1). There we have complete data. I am supplying same data, but the chart is dropping few at start
![image](https://user-images.githubusercontent.com/1359955/52365047-d4561780-2a46-11e9-8abb-068ccd6c2e4d.png)

**Comment by tanganellilore** [comment]
@otabekgb Please can you reproduce it in a jsfield or similar. 

It's diffucult debug for me without same dataset and options.
Thanks

**Comment by otabekgb** [comment]
Forget it, this is not the issue of visavail.js. I had to submit my dates in UTC. It works with UTC now
