### ISSUE TITLE
Forked repository is behind the original one

### ISSUE THREAD

**Issue by imkico** [tanganellilore/visavail#9]
Dear tanganellilore,

I'm using visavail in one of my project via npm recently, however I just realized that the version maintained on npm is behind the master branch of flrs/visavail (https://github.com/flrs/visavail), just wondering if you can get the package on npm up to date to fix some bugs with current version.

Best Regards,
Eric

**Comment by tanganellilore** [comment]
Hi,

what do you mean with "wondering if you can get the package on npm up to date to fix some bugs with current version".
This fork was aligned to flrs repo and I "maintain" the flrs repo and npm package.

Last release is 1.5.0 on flrs repo and tha sma is on npm package.

**Comment by tanganellilore** [comment]
Sorry, 

I notice now what you mean... il willt ry to relase 1.5.1.
Thanks for highlight me this.
